/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./../../src/components/Chat.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../../src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../../src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../../src/components/WelcomeItem.vue')['default']
  }
}
